import './globals.scss'
import { Inter } from 'next/font/google'
import CarbonHeader from './components/CarbonHeader'
import AuthContext from './context/AuthContext'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Academy',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <AuthContext>
        <body className={inter.className}>
          <CarbonHeader />
          {children}
        </body>
      </AuthContext>
    </html>
  )
}
